version: '3.8'

services:
  news-bot:
    image: ghcr.io/xyling12/news-aggregator-bot:main
    pull_policy: always
    container_name: news-bot
    restart: unless-stopped
    volumes:
      - bot_data:/app/data
      - bot_media:/app/media
    env_file:
      - .env
    environment:
      - AUTO_PUBLISH=true
      - PUBLISH_INTERVAL=600
      - USE_SOURCE_MEDIA=true
      - VK_GROUP_ID=236380336
      - AITUNNEL_API_KEY=sk-aitunnel-GEhq2XTu9QmIrrOZe2S1Di2WAdp7yQ0C
      - AITUNNEL_MODEL=gpt-5-mini
      - PEXELS_API_KEY=I71vTtRmVcODHWvBFyXjviye6s7c0WdrOIILXo3O4iXiArXCuVLONb5l
      - PEXELS_PROXY=http://user275577:5s18m2@45.90.197.174:6164
      - TELEGRAM_PROXY=http://user275577:5s18m2@45.90.197.174:6164
      - VK_USER_TOKEN=${VK_USER_TOKEN}
    healthcheck:
      test: [ "CMD", "python", "-c", "import sqlite3; sqlite3.connect('file:/app/data/bot.db?mode=ro', uri=True).execute('SELECT 1 FROM sources LIMIT 1')" ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - dokploy-bridge
      - dokploy-network

networks:
  dokploy-bridge:
    external: true
  dokploy-network:
    external: true

volumes:
  bot_data:
  bot_media:
